[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.7.6"
optimizer = true
optimizer_runs = 200
eth_rpc_url = "https://rpc.pulsechain.com"

[rpc_endpoints]
pulsechain = "https://rpc.pulsechain.com"

[etherscan]
pulsechain = { key = "", chain = 369, url = "https://api.scan.pulsechain.com/api" }

